version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/backend_template
      - SPRING_DATASOURCE_USERNAME=backend_user
      - SPRING_DATASOURCE_PASSWORD=backend_password
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mariadb:10.11
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=backend_template
      - MARIADB_USER=backend_user
      - MARIADB_PASSWORD=backend_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: