spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://mariadb:3306/inventory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:!jelly0403}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${BACKEND_URL:http://backend:8080}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_EXPIRATION:86400000}

app:
  frontend:
    url: ${FRONTEND_URL:http://frontend:3000}

logging:
  level:
    com.basic.template.backend_template: INFO
    org.springframework.security: WARN
    root: WARN