spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/inventory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: '!jelly0403'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

jwt:
  secret-key: mySecretKey123456789012345678901234567890
  access-token-expiration: 86400000 # 24시간

logging:
  level:
    com.basic.template.backend_template: DEBUG
    org.springframework.security: DEBUG
    root: INFO